name: .NET Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
    inputs:
      test_category:
        description: 'Test Category to run'
        required: true
        default: 'Smoke'
        type: choice
        options:
        - Smoke
        - Regression
      environment:
        description: 'Environment to run tests against'
        required: true
        default: 'test'
        type: choice
        options:
        - test
        - staging
        - production

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'test' }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./AMT.Xunit.V3.Tests

    - name: Build
      run: dotnet build --no-restore ./AMT.Xunit.V3.Tests

    - name: Echo Secret and Variable
      run: |
        echo "ENVIRONMENTSECRET: ${{ secrets.ENVIRONMENTSECRET }}"
        echo "ENVIRONMENTURL: ${{ vars.ENVIRONMENTURL }}"

    - name: Test
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          TEST_FILTER="--filter Category=${{ inputs.test_category }}"
        else
          TEST_FILTER="--filter Category=Smoke"
        fi
        dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx" $TEST_FILTER ./AMT.Xunit.V3.Tests
      env:
        DOTNET_ENVIRONMENT: ${{ inputs.environment || 'test' }}
        ENVIRONMENTSECRET: ${{ secrets.ENVIRONMENTSECRET }}
        ENVIRONMENTURL: ${{ vars.ENVIRONMENTURL }}

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: '**/TestResults/*.trx'
